# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "300"

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Deneysiz.xcodeproj")
    build_app(scheme: "Deneysiz")
    upload_to_testflight
  end

  desc 'Builds project and executes unit tests'
      lane :unit_test do |options|
        scan(
          clean: options[:clean],
          skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution]
        )
  end

  desc 'Running iOS tests using fastlane'
  lane :tests do
    run_tests(
      workspace: "Deneysiz.xcodeproj/project.xcworkspace",
      scheme: "Deneysiz",
      devices: ["iPhone 14"],
      clean: true,
      prelaunch_simulator: true,
      result_bundle: true
    )
  end

  lane :testFlight do
    match(type: "appstore", readonly: true)
    build_app
  end
end