run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  pull_request:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0-beta'
          
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Build and Upload to Testflight
        run: bundle exec fastlane runTestFlight
        env:      
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
        
        

