run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  pull_request:
    branches:
      - development
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Run Tests (No Cache)
        run: bundle exec fastlane tests
        
        

